const languages = [
  { code: "en", name: "English", country: "us" }, // Default to US for English
  { code: "es", name: "Spanish", country: "es" }, // Default to Spain for Spanish
  { code: "fr", name: "French", country: "fr" }, // Default to France for French
  { code: "pt", name: "Portuguese", country: "br" }, // Default to Brazil for Portuguese
  { code: "pt", name: "Portuguese", country: "pt" }, // Portugal for Portuguese
  { code: "de", name: "German", country: "de" },
  { code: "it", name: "Italian", country: "it" },
  { code: "zh", name: "Chinese", country: "cn" },
  { code: "ja", name: "Japanese", country: "jp" },
  { code: "ar", name: "Arabic", country: "sa" }, // Saudi Arabia for Arabic
  { code: "ru", name: "Russian", country: "ru" },
  { code: "hi", name: "Hindi", country: "in" }, // India for Hindi
  { code: "ko", name: "Korean", country: "kr" },
  { code: "tr", name: "Turkish", country: "tr" },
  { code: "nl", name: "Dutch", country: "nl" },
  { code: "sv", name: "Swedish", country: "se" },
  { code: "no", name: "Norwegian", country: "no" },
  { code: "da", name: "Danish", country: "dk" },
  { code: "fi", name: "Finnish", country: "fi" },
  { code: "pl", name: "Polish", country: "pl" },
  { code: "cs", name: "Czech", country: "cz" },
  { code: "el", name: "Greek", country: "gr" },
  { code: "he", name: "Hebrew", country: "il" },
  { code: "th", name: "Thai", country: "th" },
  { code: "vi", name: "Vietnamese", country: "vn" },
  { code: "id", name: "Indonesian", country: "id" },
  { code: "ms", name: "Malay", country: "my" },
  { code: "uk", name: "Ukrainian", country: "ua" },
  { code: "hu", name: "Hungarian", country: "hu" },
  { code: "ro", name: "Romanian", country: "ro" },
  { code: "bg", name: "Bulgarian", country: "bg" },
  { code: "sr", name: "Serbian", country: "rs" },
  { code: "hr", name: "Croatian", country: "hr" },
  { code: "sk", name: "Slovak", country: "sk" },
  { code: "sl", name: "Slovenian", country: "si" },
  { code: "et", name: "Estonian", country: "ee" },
  { code: "lv", name: "Latvian", country: "lv" },
  { code: "lt", name: "Lithuanian", country: "lt" },
  { code: "fa", name: "Persian", country: "ir" },
  { code: "ur", name: "Urdu", country: "pk" },
  { code: "bn", name: "Bengali", country: "bd" },
  { code: "ta", name: "Tamil", country: "lk" },
  { code: "te", name: "Telugu", country: "in" },
  { code: "ml", name: "Malayalam", country: "in" },
  { code: "kn", name: "Kannada", country: "in" },
  { code: "mr", name: "Marathi", country: "in" },
  { code: "gu", name: "Gujarati", country: "in" },
  { code: "pa", name: "Punjabi", country: "in" },
  { code: "tl", name: "Filipino (Tagalog)", country: "ph" },
  { code: "sw", name: "Swahili", country: "ke" },
  { code: "ht", name: "Haitian Creole", country: "ht" },
  { code: "af", name: "Afrikaans", country: "za" },
  { code: "my", name: "Burmese", country: "mm" },
  { code: "si", name: "Sinhala", country: "lk" },
  { code: "km", name: "Khmer", country: "kh" },
  { code: "lo", name: "Lao", country: "la" },
  { code: "mn", name: "Mongolian", country: "mn" },
  { code: "ka", name: "Georgian", country: "ge" },
  { code: "eu", name: "Basque", country: "es" },
  { code: "ca", name: "Catalan", country: "es" },
  { code: "other", name: "Other", country: "xx" }, // Generic "Other" with no specific country
];

module.exports = languages;
