const languages = [
  { code: "en-us", name: "English", country: "us" }, // Default to US for English
  { code: "es-es", name: "Spanish", country: "es" }, // Default to Spain for Spanish
  { code: "fr-fr", name: "French", country: "fr" }, // Default to France for French
  { code: "pt-br", name: "Portuguese (Brazil)", country: "br" }, // Brazil for Portuguese
  { code: "pt-pt", name: "Portuguese (Portugal)", country: "pt" }, // Portugal for Portuguese
  { code: "de-de", name: "German", country: "de" },
  { code: "it-it", name: "Italian", country: "it" },
  { code: "zh-cn", name: "Chinese", country: "cn" },
  { code: "ja-jp", name: "Japanese", country: "jp" },
  { code: "ar-sa", name: "Arabic", country: "sa" }, // Saudi Arabia for Arabic
  { code: "ru-ru", name: "Russian", country: "ru" },
  { code: "hi-in", name: "Hindi", country: "in" }, // India for Hindi
  { code: "ko-kr", name: "Korean", country: "kr" },
  { code: "tr-tr", name: "Turkish", country: "tr" },
  { code: "nl-nl", name: "Dutch", country: "nl" },
  { code: "sv-se", name: "Swedish", country: "se" },
  { code: "no-no", name: "Norwegian", country: "no" },
  { code: "da-dk", name: "Danish", country: "dk" },
  { code: "fi-fi", name: "Finnish", country: "fi" },
  { code: "pl-pl", name: "Polish", country: "pl" },
  { code: "cs-cz", name: "Czech", country: "cz" },
  { code: "el-gr", name: "Greek", country: "gr" },
  { code: "he-il", name: "Hebrew", country: "il" },
  { code: "th-th", name: "Thai", country: "th" },
  { code: "vi-vn", name: "Vietnamese", country: "vn" },
  { code: "id-id", name: "Indonesian", country: "id" },
  { code: "ms-my", name: "Malay", country: "my" },
  { code: "uk-ua", name: "Ukrainian", country: "ua" },
  { code: "hu-hu", name: "Hungarian", country: "hu" },
  { code: "ro-ro", name: "Romanian", country: "ro" },
  { code: "bg-bg", name: "Bulgarian", country: "bg" },
  { code: "sr-rs", name: "Serbian", country: "rs" },
  { code: "hr-hr", name: "Croatian", country: "hr" },
  { code: "sk-sk", name: "Slovak", country: "sk" },
  { code: "sl-si", name: "Slovenian", country: "si" },
  { code: "et-ee", name: "Estonian", country: "ee" },
  { code: "lv-lv", name: "Latvian", country: "lv" },
  { code: "lt-lt", name: "Lithuanian", country: "lt" },
  { code: "fa-ir", name: "Persian", country: "ir" },
  { code: "ur-pk", name: "Urdu", country: "pk" },
  { code: "bn-bd", name: "Bengali", country: "bd" },
  { code: "ta-lk", name: "Tamil", country: "lk" },
  { code: "te-in", name: "Telugu", country: "in" },
  { code: "ml-in", name: "Malayalam", country: "in" },
  { code: "kn-in", name: "Kannada", country: "in" },
  { code: "mr-in", name: "Marathi", country: "in" },
  { code: "gu-in", name: "Gujarati", country: "in" },
  { code: "pa-in", name: "Punjabi", country: "in" },
  { code: "tl-ph", name: "Filipino (Tagalog)", country: "ph" },
  { code: "sw-ke", name: "Swahili", country: "ke" },
  { code: "ht-ht", name: "Haitian Creole", country: "ht" },
  { code: "af-za", name: "Afrikaans", country: "za" },
  { code: "my-mm", name: "Burmese", country: "mm" },
  { code: "si-lk", name: "Sinhala", country: "lk" },
  { code: "km-kh", name: "Khmer", country: "kh" },
  { code: "lo-la", name: "Lao", country: "la" },
  { code: "mn-mn", name: "Mongolian", country: "mn" },
  { code: "ka-ge", name: "Georgian", country: "ge" },
  { code: "eu-es", name: "Basque", country: "es" },
  { code: "ca-es", name: "Catalan", country: "es" },
  { code: "other-xx", name: "Other", country: "xx" }, // Generic "Other" with no specific country
];

module.exports = languages;
